### ISSUE TITLE
ATT&CK v9 updates

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa-rules#342]
meta issue for tracking work on ATT&CK v9 update and ensuring coverage by capa rules. update this issue directly with details and links to other issues.

sources:
  - MITRE blog: https://medium.com/mitre-attack/attack-april-2021-release-39accaf23c81
  - Updates: https://attack.mitre.org/resources/updates/

Changes include: 
  - No new tactics
  - 7 new techniques
  - 15 new sub-techniques
  - 3 new platforms (IaaS (replacing AWS, GCP, and Azure), Google Workspace, and Containers)
  - 120 technique/sub-technique changes
  - 129 minor technique/sub-technique changes 
  - No technique/sub-technique revocations or deprecations

new techniques:

  - [x] Boot or Logon Autostart Execution: Active Setup #343
  - [x] Boot or Logon Autostart Execution: XDG Autostart Entries #344
  - [x] docker:
    - [x] Build Image on Host #345
    - [x] Container Administration Command #346
    - [x] Container and Resource Discovery #347
    - [x] Unsecured Credentials: Container API #363
    - [x] User Execution: Malicious Image #364
    - [x] Deploy Container #350 
    - [x] Escape to Host #351
    - [x] Scheduled Task/Job: Container Orchestration Job #352
  - [x] Credentials from Password Stores: Password Managers #348
  - [x] Credentials from Password Stores: Windows Credential Manager #349
  - [x]  Stage Capabilities #353
    - [x]   Drive-by Target #354
    - [x]   Install Digital Certificate #355
    - [x]   Link Target #356
    - [x]   Upload Malware #357
    - [x]   Upload Tool #358
  - [x] Subvert Trust Controls: Code Signing Policy Modification #359
  - [x] Subvert Trust Controls: Mark-of-the-Web Bypass #360
  - [x] System Location Discovery #361
  - [x] System Network Configuration Discovery: Internet Connection Discovery #362

**Comment by mr-tz** [comment]
great job everyone, we have coverage for all techniques that are in scope for capa
